version: '3'

services:
  rest-api:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 5003:5002 

  webapp:
    build: ./frontend/build
    volumes:
      - ./frontend/build:/var/www
    ports:
      - 5004:80
    depends_on:
      - rest-api
    