version: '3'

services:
  webapp:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 5001:3000

  rest-api:
    env_file:
      - ./backend/.env.test
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 5002:5002
    depends_on:
      - webapp