version: '3'

services:
  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=afmdev
      - POSTGRES_PASSWORD=afmdevpass
      - POSTGRES_DB=afmtestdb
    expose:
      - 5432

  rest-api:
    env_file:
      - ./backend/.env.test
    build: ./backend
    ports:
      - 5002:5002
    depends_on:
      - db

  webapp:
    build: ./frontend
    ports:
      - 5001:3000
    depends_on:
      - rest-api


    