version: '3'

services:
  rest-api:
    env_file:
      - ./backend/.env.prod
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 5002:5002 

  webapp:
    build: ./frontend/build
    volumes:
      - ./frontend/build:/var/www
    ports:
      - 5001:80
    depends_on:
      - rest-api
    