version: '3'

services:
  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=afmdev
      - POSTGRES_PASSWORD=afmdevpass
      - POSTGRES_DB=afmdb
    volumes:
      - ./__postgres-data__:/var/lib/postgresql/data
    expose:
      - 5432

  rest-api:
    env_file:
      - ./.env.dev
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - 5002:5002 
    depends_on:
      - db
    